name: Release Model-Service

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (PR only)
        # This step runs only for pull requests. It builds the image but doesn't push it,
        # acting as a validation step. 'load: true' makes the image available to subsequent steps if needed.
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true

      - name: Build and push (tags or manual)
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/model-service:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/model-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-release-and-bump:
    # This job only runs when a tag is pushed. 
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Create GitHub Release (stable)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine next prerelease version
        id: next_prerelease
        run: |
          version=${GITHUB_REF#refs/tags/v}
          base_version=$(echo "$version" | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          
          latest_prerelease_tag=$(git tag --list "v${base_version}-rc.*" | sort -V | tail -n 1)
          
          rc_number=1
          if [[ -n "$latest_prerelease_tag" ]]; then
            latest_rc_number=$(echo "$latest_prerelease_tag" | grep -oP 'rc\.\K\d+')
            rc_number=$((latest_rc_number + 1))
          fi
          
          # Construct the new prerelease version string (e.g., v0.1.5-rc.3)
          next="v${base_version}-rc.${rc_number}"
          echo "next_release=$next" >> $GITHUB_OUTPUT

      - name: Bump version in metadata
        run: |
          # Write the new prerelease version to a VERSION file
          echo "${{ steps.next_prerelease.outputs.next_release }}" > VERSION

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add VERSION
          
          git commit -m "chore: bump to prerelease ${{ steps.next_prerelease.outputs.next_release }}"
          
          git tag ${{ steps.next_prerelease.outputs.next_release }}
          
          git push origin HEAD:main --follow-tags

      - name: Create prerelease GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.next_prerelease.outputs.next_release }}
          name: Pre-release ${{ steps.next_prerelease.outputs.next_release }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}